/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBar: typeof import('./src/components/StatusBar.vue')['default']
    UartInput: typeof import('./src/components/UartInput.vue')['default']
    UartLog: typeof import('./src/components/UartLog.vue')['default']
    VirtualKeyboard: typeof import('./src/components/VirtualKeyboard.vue')['default']
  }
}
