name: ESP-IDF build
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build_esp32:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 21
        cache: npm
    - name: Build front
      working-directory: ./front/kespr3m0
      run: npm ci && npm run build
    - name: ESP-IDF v5.2.1 build esp32s3
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.2.1
        target: esp32s3
        command: 'idf.py set-target esp32s3 build'
